config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :gifs
  resources :users, only: [:index, :show]

  get '*tag', to: 'gifs#random', as: :random_gif
  root to: 'gifs#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gif.rb
class Gif < ApplicationRecord
  include ImageUploader::Attachment(:image)

  belongs_to :user
  acts_as_taggable

  scope :sorted, -> { order(created_at: :desc) }

  def self.random
    order("RANDOM()").first
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_person_name
  has_many :gifs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/gifs_controller.rb
class GifsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :random]
  before_action :set_gif, only: [:edit, :update, :destroy]

  # GET /gifs
  # GET /gifs.json
  def index
    @gifs = Gif.includes(:tags, :user).sorted
  end

  # GET /gifs/1
  # GET /gifs/1.json
  def show
    @gif = Gif.find(params[:id])
  end

  def random
    @gif = Gif.tagged_with(params[:tag]).random
    @gif ||= Gif.random
    render :show
  end

  # GET /gifs/new
  def new
    @gif = Gif.new
  end

  # GET /gifs/1/edit
  def edit
  end

  # POST /gifs
  # POST /gifs.json
  def create
    @gif = current_user.gifs.new(gif_params)

    respond_to do |format|
      if @gif.save
        format.html { redirect_to @gif, notice: 'Gif was successfully created.' }
        format.json { render :show, status: :created, location: @gif }
      else
        format.html { render :new }
        format.json { render json: @gif.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gifs/1
  # PATCH/PUT /gifs/1.json
  def update
    respond_to do |format|
      if @gif.update(gif_params)
        format.html { redirect_to @gif, notice: 'Gif was successfully updated.' }
        format.json { render :show, status: :ok, location: @gif }
      else
        format.html { render :edit }
        format.json { render json: @gif.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gifs/1
  # DELETE /gifs/1.json
  def destroy
    @gif.destroy
    respond_to do |format|
      format.html { redirect_to gifs_url, notice: 'Gif was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gif
      @gif = current_user.gifs.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def gif_params
      permitted = [:tag_list]
      permitted += [:image] if action_name == 'new'
      params.require(:gif).permit(*permitted)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user

  def index
    redirect_to root_path
  end

  def show
    @gifs = @user.gifs.includes(:tags, :user).sorted
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gifs_helper.rb
module GifsHelper

  def linked_tag_list(gif)
    list = gif.tags.map do |tag|
      link_to tag, random_gif_path(tag: tag)
    end

    safe_join list, ", "
  end

  def full_gif_url(gif)
    gif.image_url(host: request.protocol + request.host_with_port)
  end
end

app/views/gifs/_form.html.erb
<div class="w-full max-w-sm mx-auto">
  <%= form_with(model: gif, local: true) do |form| %>
    <% if gif.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(gif.errors.count, "error") %> prohibited this gif from being saved:</h2>

        <ul>
          <% gif.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="mb-6">
      <% if form.object.persisted? %>
        <%= image_tag form.object.image_url %>
      <% else %>
        <label class="block text-gray-500 font-bold mb-1">
          <%= form.label :image %>
        </label>

        <%= form.hidden_field :image, value: form.object.cached_image_data %>
        <%= form.file_field :image, class: "appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight border-4 border-dashed border-gray-200 rounded-lg" %>
      <% end %>
    </div>

    <div class="mb-6">
      <label class="block text-gray-500 font-bold mb-1">
        <%= form.label :tag_list, "Tag list (comma separated)" %>
      </label>

      <%= form.text_field :tag_list, value: form.object.tag_list.join(", "), class: "bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500" %>
    </div>

    <div class="w-full flex justify-between">
      <div>
        <%= form.submit class: "shadow bg-purple-500 hover:bg-purple-400 focus:shadow-outline focus:outline-none text-white font-bold py-2 px-4 rounded mr-2" %>
        <%= link_to "Cancel", (@gif.persisted? ? @gif : root_path) %>
      </div>

      <%= link_to 'Destroy', @gif, method: :delete, data: { confirm: 'Are you sure?' }, class: "shadow bg-red-500 hover:bg-red-400 focus:shadow-outline focus:outline-none text-white font-bold py-2 px-4 rounded" if @gif.persisted? %>
    </div>
  <% end %>
</div>

app/views/gifs/_gif.html.erb
<div class="w-64 m-2 border rounded shadow flex flex-col justify-between">
  <%= link_to image_tag(gif.image_url, class: "mx-auto"), gif, class: "block bg-black" %>
  <div class="p-2 text-sm text-center">
    <%= link_to linked_tag_list gif %>
    <p class="mb-2">This was uploaded by <%= link_to gif.user.name, gif.user %></p>
  </div>
</div>

app/views/gifs/edit.html.erb
<h1 class="text-3xl text-center font-bold uppercase pb-12">Editing Gif</h1>

<%= render 'form', gif: @gif %>

app/views/gifs/index.html.erb
<h1 class="text-3xl text-center font-bold uppercase py-12">Gifs</h1>

<div class="flex flex-wrap justify-center">
  <%= render @gifs %>
</div>

app/views/gifs/new.html.erb
<h1 class="text-3xl text-center font-bold uppercase pb-12">New Gif</h1>

<%= render 'form', gif: @gif %>

app/views/gifs/show.html.erb
<div class="mb-6">
  <%= image_tag @gif.image_url %>
</div>

<div class="bg-gray-200 rounded p-4 mb-10">
  <p class="mb-2">This was uploaded by <strong><%= link_to @gif.user.name, @gif.user %></strong></p>
  <p>Gif tags: <span class="text-sm"><%= linked_tag_list @gif %></span></p>

  <hr class="my-6" />

  <div data-controller="clipboard" class="flex">
    <%= text_field_tag nil, full_gif_url(@gif), data: { target: "clipboard.source" }, class: "bg-gray-300 appearance-none border-2 border-gray-300 rounded flex-grow py-2 px-4 mr-2 text-gray-700 leading-tight focus:outline-none focus:border-purple-500", readonly: true %>
    <button data-action="click->clipboard#copy" data-target="clipboard.button" class="shadow bg-purple-500 hover:bg-purple-400 focus:shadow-outline focus:outline-none text-white font-bold py-2 px-4 rounded">
      Copy
    </button>
  </div>
</div>

<% if user_signed_in? && current_user == @gif.user %>
  <%= link_to 'Edit', edit_gif_path(@gif), class: "shadow bg-purple-500 hover:bg-purple-400 focus:shadow-outline focus:outline-none text-white font-bold py-2 px-4 rounded" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en" class="bg-white antialiased">
  <head>
    <title>AnimatedgifMe</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/shared/navigation" %>

    <div class="container mx-auto mt-10 px-6">
      <div>
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
      </div>

      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/shared/_navigation.html.erb
<div class="block flex bg-white border-b border-gray-200 h-16 items-center">
  <div class="w-full max-w-screen-xl relative mx-auto px-6">
    <div class="block flex items-center -mx-6">
      <div class="flex-grow">
        <div class="flex items-center">
          <%= link_to "AnimatedGif.me", root_path, class: "block lg:mr-4" %>
        </div>
      </div>

      <div class="text-right">
        <%= link_to 'New Gif', new_gif_path, class: "bg-purple-500 hover:bg-purple-400 focus:shadow-outline focus:outline-none text-white font-bold py-2 px-4 rounded mr-4" %>

        <% if user_signed_in? %>
          <%= link_to 'My Gifs', current_user, class: "text-gray-700 hover:text-gray-800 font-bold mr-4" %>
          <%= link_to "Account", edit_user_registration_path, class: "text-gray-700 hover:text-gray-800 font-bold mr-4" %>
          <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "text-gray-700 hover:text-gray-800 font-bold mr-4" %>
        <% else %>
          <%= link_to "Sign up", new_user_registration_path, class: "text-gray-600 hover:text-gray-700 mr-4" %>
          <%= link_to "Login", new_user_session_path, class: "text-gray-600 hover:text-gray-700" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h1 class="text-3xl text-center font-bold uppercase py-12">
  <%= @user.name %> Gifs
</h1>

<div class="flex flex-wrap justify-center">
  <%= render @gifs %>
</div>